package modelo.entidad;
// Generated 1 dic. 2019 19:14:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aerolinea generated by hbm2java
 */
public class Aerolinea  implements java.io.Serializable {


     private Integer idAerolinea;
     private String nombre;
     private String telefono;
     private Set<Vuelo> vuelos = new HashSet<Vuelo>(0);

    public Aerolinea() {
    }

    public Aerolinea(String nombre, String telefono, Set<Vuelo> vuelos) {
       this.nombre = nombre;
       this.telefono = telefono;
       this.vuelos = vuelos;
    }
   
    public Integer getIdAerolinea() {
        return this.idAerolinea;
    }
    
    public void setIdAerolinea(Integer idAerolinea) {
        this.idAerolinea = idAerolinea;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Vuelo> getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set<Vuelo> vuelos) {
        this.vuelos = vuelos;
    }




}


