package modelo.entidad;
// Generated 1 dic. 2019 19:14:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clase generated by hbm2java
 */
public class Clase  implements java.io.Serializable {


     private Integer idClase;
     private Character tipo;
     private String descripcion;
     private Set<VueloClase> vueloClases = new HashSet<VueloClase>(0);

    public Clase() {
    }

    public Clase(Character tipo, String descripcion, Set<VueloClase> vueloClases) {
       this.tipo = tipo;
       this.descripcion = descripcion;
       this.vueloClases = vueloClases;
    }
   
    public Integer getIdClase() {
        return this.idClase;
    }
    
    public void setIdClase(Integer idClase) {
        this.idClase = idClase;
    }
    public Character getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Character tipo) {
        this.tipo = tipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<VueloClase> getVueloClases() {
        return this.vueloClases;
    }
    
    public void setVueloClases(Set<VueloClase> vueloClases) {
        this.vueloClases = vueloClases;
    }




}


