package modelo.entidad;
// Generated 1 dic. 2019 19:14:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String nombre;
     private String apellido;
     private String numeroIdentificacion;
     private String tipoIdentificacion;
     private String nacionalidad;
     private String telefono;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public Cliente() {
    }

    public Cliente(String nombre, String apellido, String numeroIdentificacion, String tipoIdentificacion, String nacionalidad, String telefono, Set<Reserva> reservas) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.numeroIdentificacion = numeroIdentificacion;
       this.tipoIdentificacion = tipoIdentificacion;
       this.nacionalidad = nacionalidad;
       this.telefono = telefono;
       this.reservas = reservas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNumeroIdentificacion() {
        return this.numeroIdentificacion;
    }
    
    public void setNumeroIdentificacion(String numeroIdentificacion) {
        this.numeroIdentificacion = numeroIdentificacion;
    }
    public String getTipoIdentificacion() {
        return this.tipoIdentificacion;
    }
    
    public void setTipoIdentificacion(String tipoIdentificacion) {
        this.tipoIdentificacion = tipoIdentificacion;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


