package modelo.entidad;
// Generated 1 dic. 2019 19:14:27 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Origen generated by hbm2java
 */
public class Origen  implements java.io.Serializable {


     private Integer idOrigen;
     private String pais;
     private String ciudad;
     private String aeropuerto;
     private Set<Vuelo> vuelos = new HashSet<Vuelo>(0);

    public Origen() {
    }

    public Origen(String pais, String ciudad, String aeropuerto, Set<Vuelo> vuelos) {
       this.pais = pais;
       this.ciudad = ciudad;
       this.aeropuerto = aeropuerto;
       this.vuelos = vuelos;
    }
   
    public Integer getIdOrigen() {
        return this.idOrigen;
    }
    
    public void setIdOrigen(Integer idOrigen) {
        this.idOrigen = idOrigen;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getAeropuerto() {
        return this.aeropuerto;
    }
    
    public void setAeropuerto(String aeropuerto) {
        this.aeropuerto = aeropuerto;
    }
    public Set<Vuelo> getVuelos() {
        return this.vuelos;
    }
    
    public void setVuelos(Set<Vuelo> vuelos) {
        this.vuelos = vuelos;
    }




}


