package modelo.entidad;
// Generated 1 dic. 2019 19:14:27 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idReserva;
     private Cliente cliente;
     private Usuario usuario;
     private VueloClase vueloClase;
     private Integer cantidadPersonas;
     private Integer formaPago;
     private String tipoReserva;
     private Date fechaCreacion;

    public Reserva() {
    }

    public Reserva(Cliente cliente, Usuario usuario, VueloClase vueloClase, Integer cantidadPersonas, Integer formaPago, String tipoReserva, Date fechaCreacion) {
       this.cliente = cliente;
       this.usuario = usuario;
       this.vueloClase = vueloClase;
       this.cantidadPersonas = cantidadPersonas;
       this.formaPago = formaPago;
       this.tipoReserva = tipoReserva;
       this.fechaCreacion = fechaCreacion;
    }
   
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public VueloClase getVueloClase() {
        return this.vueloClase;
    }
    
    public void setVueloClase(VueloClase vueloClase) {
        this.vueloClase = vueloClase;
    }
    public Integer getCantidadPersonas() {
        return this.cantidadPersonas;
    }
    
    public void setCantidadPersonas(Integer cantidadPersonas) {
        this.cantidadPersonas = cantidadPersonas;
    }
    public Integer getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(Integer formaPago) {
        this.formaPago = formaPago;
    }
    public String getTipoReserva() {
        return this.tipoReserva;
    }
    
    public void setTipoReserva(String tipoReserva) {
        this.tipoReserva = tipoReserva;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


