package modelo.entidad;
// Generated 1 dic. 2019 19:14:27 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VueloClase generated by hbm2java
 */
public class VueloClase  implements java.io.Serializable {


     private Integer idVueloClase;
     private Clase clase;
     private Vuelo vuelo;
     private Integer numeroAsientos;
     private Double precio;
     private Double precioComida;
     private Date fechaCreacion;
     private Set<Reserva> reservas = new HashSet<Reserva>(0);

    public VueloClase() {
    }

    public VueloClase(Clase clase, Vuelo vuelo, Integer numeroAsientos, Double precio, Double precioComida, Date fechaCreacion, Set<Reserva> reservas) {
       this.clase = clase;
       this.vuelo = vuelo;
       this.numeroAsientos = numeroAsientos;
       this.precio = precio;
       this.precioComida = precioComida;
       this.fechaCreacion = fechaCreacion;
       this.reservas = reservas;
    }
   
    public Integer getIdVueloClase() {
        return this.idVueloClase;
    }
    
    public void setIdVueloClase(Integer idVueloClase) {
        this.idVueloClase = idVueloClase;
    }
    public Clase getClase() {
        return this.clase;
    }
    
    public void setClase(Clase clase) {
        this.clase = clase;
    }
    public Vuelo getVuelo() {
        return this.vuelo;
    }
    
    public void setVuelo(Vuelo vuelo) {
        this.vuelo = vuelo;
    }
    public Integer getNumeroAsientos() {
        return this.numeroAsientos;
    }
    
    public void setNumeroAsientos(Integer numeroAsientos) {
        this.numeroAsientos = numeroAsientos;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Double getPrecioComida() {
        return this.precioComida;
    }
    
    public void setPrecioComida(Double precioComida) {
        this.precioComida = precioComida;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public Set<Reserva> getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set<Reserva> reservas) {
        this.reservas = reservas;
    }




}


